// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ca27US6C6wuniG46Lxjxb
// Component: DnR4YQT_sRSg
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_46Mvvy7O4Urob } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 46MVVY7o4Urob/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_pevilab.module.css"; // plasmic-import: ca27US6C6wuniG46Lxjxb/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: DnR4YQT_sRSg/css
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: Fy1Z1kyIlI/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: jGzSkGR0H7U/icon
import RedHeartIcon1Icon from "./icons/PlasmicIcon__RedHeartIcon1"; // plasmic-import: X4qS5l_i029/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: QgnsOgZI4DZ/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: iYiZSj2ryD7/icon
import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: Hs-8WtobFfl/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: nC-JmxhyvD9/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: AIDKqVXfyCQ/icon
import Ellipse4Icon from "./icons/PlasmicIcon__Ellipse4"; // plasmic-import: 3Ja9os5OsSN/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: 41tcLsJpRQG/icon
import ThinLongArrowRightIcon1Icon from "./icons/PlasmicIcon__ThinLongArrowRightIcon1"; // plasmic-import: Q3CNOLw7Hn6/icon
import Ellipse8Icon from "./icons/PlasmicIcon__Ellipse8"; // plasmic-import: 0zxct5o_BgV/icon
import Xmlid826Icon from "./icons/PlasmicIcon__Xmlid826"; // plasmic-import: p2FWTUycmKW/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: bQAfSit5f39/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: AjoM9kMSRkx/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: O22RGAAcPEm/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: krYIVr6fG3l/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: _s75IgaNj7H/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: MLcrECfOLVr/icon
import Ellipse9Icon from "./icons/PlasmicIcon__Ellipse9"; // plasmic-import: yoIxLNnuvDP/icon
import Ellipse10Icon from "./icons/PlasmicIcon__Ellipse10"; // plasmic-import: Oq6CchhA5Av/icon
import Ellipse11Icon from "./icons/PlasmicIcon__Ellipse11"; // plasmic-import: eeEsPVsqmbd/icon
import Ellipse12Icon from "./icons/PlasmicIcon__Ellipse12"; // plasmic-import: 8uHDDoaKE5y/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: 6j2oRuSe7M1/icon
import Group5Icon from "./icons/PlasmicIcon__Group5"; // plasmic-import: HCVBh9_Z2ZF/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: CU5I9sD-7/icon
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: G9pd9LJCUy/icon
import Ellipse13Icon from "./icons/PlasmicIcon__Ellipse13"; // plasmic-import: VwFdtd7uJI/icon
import RedHeartIcon2Icon from "./icons/PlasmicIcon__RedHeartIcon2"; // plasmic-import: l6jftlsrNz/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: DKKxNUbQus/icon
import Line7Icon from "./icons/PlasmicIcon__Line7"; // plasmic-import: zTmwLbxQZl/icon
import ThinLongArrowRightIcon2Icon from "./icons/PlasmicIcon__ThinLongArrowRightIcon2"; // plasmic-import: nJpPU_pBPH/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_46Mvvy7O4Urob()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"webpage"}
              data-plasmic-override={overrides.webpage}
              className={classNames(projectcss.all, sty.webpage)}
            >
              <div
                data-plasmic-name={"bg"}
                data-plasmic-override={overrides.bg}
                className={classNames(projectcss.all, sty.bg)}
              />

              <div
                data-plasmic-name={"blur1"}
                data-plasmic-override={overrides.blur1}
                className={classNames(projectcss.all, sty.blur1)}
              />

              <div
                data-plasmic-name={"blur2"}
                data-plasmic-override={overrides.blur2}
                className={classNames(projectcss.all, sty.blur2)}
              />

              <div
                data-plasmic-name={"blur4"}
                data-plasmic-override={overrides.blur4}
                className={classNames(projectcss.all, sty.blur4)}
              />

              <div
                data-plasmic-name={"blur6"}
                data-plasmic-override={overrides.blur6}
                className={classNames(projectcss.all, sty.blur6)}
              />

              <div
                data-plasmic-name={"blur5"}
                data-plasmic-override={overrides.blur5}
                className={classNames(projectcss.all, sty.blur5)}
              />

              <div
                data-plasmic-name={"blur3"}
                data-plasmic-override={overrides.blur3}
                className={classNames(projectcss.all, sty.blur3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nhYfq
                )}
              >
                {"Pevilab"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h4S6A
                )}
              >
                {"Home"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pWYc
                )}
              >
                {"About Us"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pPVl
                )}
              >
                {"Projects"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cUkUg
                )}
              >
                {"Contact"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4Fm7Y
                )}
              >
                {"En."}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l2GX
                )}
              >
                {"Fr."}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__y7P7W)}
                displayHeight={"14px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"14px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/pevilab/images/ellipse1.svg",
                  fullWidth: 14,
                  fullHeight: 14,
                  aspectRatio: 1
                }}
              />

              <Line1Icon
                className={classNames(projectcss.all, sty.svg__ns2K8)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tgav1
                )}
              >
                {"Trust by 100+ of Companies"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oacwH
                )}
              >
                {"Simplify Intricate\nApplications For\nUsers"}
              </div>

              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />

              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r8Hbf
                )}
              >
                {"Learn More"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x3Ety
                )}
              >
                {"Contact Us"}
              </div>

              <div
                data-plasmic-name={"blackPic1"}
                data-plasmic-override={overrides.blackPic1}
                className={classNames(projectcss.all, sty.blackPic1)}
              />

              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(projectcss.all, sty.rectangle6)}
              />

              <Ellipse2Icon
                className={classNames(projectcss.all, sty.svg__wIIgY)}
                role={"img"}
              />

              <RedHeartIcon1Icon
                className={classNames(projectcss.all, sty.svg__euyD)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5ByIo
                )}
              >
                {"100+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oadWt
                )}
              >
                {"Company Projects"}
              </div>

              <div
                data-plasmic-name={"line"}
                data-plasmic-override={overrides.line}
                className={classNames(projectcss.all, sty.line)}
              />

              <div
                data-plasmic-name={"line2"}
                data-plasmic-override={overrides.line2}
                className={classNames(projectcss.all, sty.line2)}
              />

              <div
                data-plasmic-name={"rectangle7"}
                data-plasmic-override={overrides.rectangle7}
                className={classNames(projectcss.all, sty.rectangle7)}
              />

              <div
                data-plasmic-name={"rectangle8"}
                data-plasmic-override={overrides.rectangle8}
                className={classNames(projectcss.all, sty.rectangle8)}
              />

              <div
                data-plasmic-name={"rectangle9"}
                data-plasmic-override={overrides.rectangle9}
                className={classNames(projectcss.all, sty.rectangle9)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qextE
                )}
              >
                {"10+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y5Ett
                )}
              >
                {"25+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xyRjI
                )}
              >
                {"Years Of Experience"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tbQc1
                )}
              >
                {"Trusted Partners"}
              </div>

              <VectorIcon
                className={classNames(projectcss.all, sty.svg__lz0D6)}
                role={"img"}
              />

              <div
                data-plasmic-name={"qualityBadgeStarIcon"}
                data-plasmic-override={overrides.qualityBadgeStarIcon}
                className={classNames(projectcss.all, sty.qualityBadgeStarIcon)}
              >
                <GroupIcon
                  className={classNames(projectcss.all, sty.svg__mWPtR)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"r1"}
                data-plasmic-override={overrides.r1}
                className={classNames(projectcss.all, sty.r1)}
              >
                <div
                  data-plasmic-name={"lline1"}
                  data-plasmic-override={overrides.lline1}
                  className={classNames(projectcss.all, sty.lline1)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Vrow
                  )}
                >
                  {"Web UI/UX\nDesign"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ywbLq
                  )}
                >
                  {"Explore"}
                </div>

                <Line2Icon
                  className={classNames(projectcss.all, sty.svg__fudg)}
                  role={"img"}
                />

                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__doA2S)}
                  role={"img"}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cbqEo)}
                  displayHeight={"18px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/pevilab/images/thinArrowRightIcon1.svg",
                    fullWidth: 22,
                    fullHeight: 18,
                    aspectRatio: 1.222222
                  }}
                />
              </div>

              <div
                data-plasmic-name={"r12"}
                data-plasmic-override={overrides.r12}
                className={classNames(projectcss.all, sty.r12)}
              >
                <div
                  data-plasmic-name={"lline2"}
                  data-plasmic-override={overrides.lline2}
                  className={classNames(projectcss.all, sty.lline2)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ekrD
                  )}
                >
                  {"Web & Mobile\nDevelopment"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w9T39
                  )}
                >
                  {"Explore"}
                </div>

                <Line2Icon
                  className={classNames(projectcss.all, sty.svg__np3I1)}
                  role={"img"}
                />

                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg___0TQxr)}
                  role={"img"}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__epRo0)}
                  displayHeight={"18px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/pevilab/images/thinArrowRightIcon2.svg",
                    fullWidth: 22,
                    fullHeight: 18,
                    aspectRatio: 1.222222
                  }}
                />
              </div>

              <div
                data-plasmic-name={"r13"}
                data-plasmic-override={overrides.r13}
                className={classNames(projectcss.all, sty.r13)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__n0Vk7
                  )}
                >
                  {"Brand Identity Design,\n& 3D Design"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tmffT
                  )}
                >
                  {"Explore"}
                </div>

                <Line3Icon
                  className={classNames(projectcss.all, sty.svg___9HsCx)}
                  role={"img"}
                />

                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__hlsAw)}
                  role={"img"}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__aue4V)}
                  displayHeight={"18px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/pevilab/images/thinArrowRightIcon3.svg",
                    fullWidth: 22,
                    fullHeight: 18,
                    aspectRatio: 1.222222
                  }}
                />
              </div>

              <div
                data-plasmic-name={"r14"}
                data-plasmic-override={overrides.r14}
                className={classNames(projectcss.all, sty.r14)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nqFxp
                  )}
                >
                  {"Proven Track Records"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gPot5
                  )}
                >
                  {"Specialized Experts"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6Asxi
                  )}
                >
                  {"Innovative Thinking"}
                </div>

                <Ellipse4Icon
                  className={classNames(projectcss.all, sty.svg__unjCy)}
                  role={"img"}
                />

                <Ellipse4Icon
                  className={classNames(projectcss.all, sty.svg__x1GeO)}
                  role={"img"}
                />

                <Ellipse4Icon
                  className={classNames(projectcss.all, sty.svg__oUySz)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__j6I9C
                  )}
                >
                  {"01"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s4NVk
                  )}
                >
                  {"02"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pOtA3
                  )}
                >
                  {"03"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ppkZu
                  )}
                >
                  {
                    "We have a portfolio of successful projects and campaigns we’ve completed\nfor previous clients, this prove our ability of consistent quality work and results."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aFpEa
                  )}
                >
                  {
                    "Pevilab is a team of specialized experts that have several experience and \nknowledge in their area of field such as web development, designs and more."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2DTb4
                  )}
                >
                  {
                    "We provide fresh and Innovative ideas that makes businesses stand out from \ntheir competitors and help connect them with their ideal customers."
                  }
                </div>

                <Line4Icon
                  className={classNames(projectcss.all, sty.svg__rW7AS)}
                  role={"img"}
                />

                <Line4Icon
                  className={classNames(projectcss.all, sty.svg__pkb5P)}
                  role={"img"}
                />

                <Line4Icon
                  className={classNames(projectcss.all, sty.svg__sdunc)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"rectangle14"}
                data-plasmic-override={overrides.rectangle14}
                className={classNames(projectcss.all, sty.rectangle14)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r7R4
                )}
              >
                {
                  "See what our clients have to say about their journey with us."
                }
              </div>

              <div
                data-plasmic-name={"rectangle10"}
                data-plasmic-override={overrides.rectangle10}
                className={classNames(projectcss.all, sty.rectangle10)}
              />

              <div
                data-plasmic-name={"_16784072378991"}
                data-plasmic-override={overrides._16784072378991}
                className={classNames(projectcss.all, sty._16784072378991)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rSj4E
                )}
              >
                {"We Design Digital\nProducts, Brands and\nExperience"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iaoDe
                )}
              >
                {"Why Choose Us?"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___70QkT
                )}
              >
                {"Testimonials"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4NClc
                )}
              >
                {"Explore Our Services"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8HeIt
                )}
              >
                {
                  "We are a full-service creative agency, with teams of \ntalented experts ready to help you build your product.\nWe work closely with clients to understand their expertise\nto develop effective and engaging solutions that help\nbusinesses stand out in the competitive market."
                }
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ngjnP
                )}
              >
                {"See More"}
              </div>

              <ThinLongArrowRightIcon1Icon
                className={classNames(projectcss.all, sty.svg__f1Vlg)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z2ESu
                )}
              >
                {"Meet Our Team"}
              </div>

              <div
                data-plasmic-name={"ay"}
                data-plasmic-override={overrides.ay}
                className={classNames(projectcss.all, sty.ay)}
              >
                <div
                  data-plasmic-name={"_16784110698861"}
                  data-plasmic-override={overrides._16784110698861}
                  className={classNames(projectcss.all, sty._16784110698861)}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5Ylnt
                )}
              >
                {"A Digital Designer"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rosKj
                )}
              >
                {
                  "He has strong ability to collaborate and\ncommunicate with cross functional teams, including developers, project managers and stakeholders.."
                }
              </div>

              <div
                data-plasmic-name={"ay2"}
                data-plasmic-override={overrides.ay2}
                className={classNames(projectcss.all, sty.ay2)}
              >
                <div
                  data-plasmic-name={"_16784110698862"}
                  data-plasmic-override={overrides._16784110698862}
                  className={classNames(projectcss.all, sty._16784110698862)}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xqLmq
                )}
              >
                {"A Digital Designer"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r5UzF
                )}
              >
                {
                  "He has strong ability to collaborate and\ncommunicate with cross functional teams, including developers, project managers and stakeholders.."
                }
              </div>

              <div
                data-plasmic-name={"wonder"}
                data-plasmic-override={overrides.wonder}
                className={classNames(projectcss.all, sty.wonder)}
              >
                <div
                  data-plasmic-name={"_1678444491112"}
                  data-plasmic-override={overrides._1678444491112}
                  className={classNames(projectcss.all, sty._1678444491112)}
                />
              </div>

              <div
                data-plasmic-name={"mekus"}
                data-plasmic-override={overrides.mekus}
                className={classNames(projectcss.all, sty.mekus)}
              >
                <div
                  data-plasmic-name={"_1678444491125"}
                  data-plasmic-override={overrides._1678444491125}
                  className={classNames(projectcss.all, sty._1678444491125)}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tm20W
                )}
              >
                {"Wondr"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gmbNt
                )}
              >
                {"Mekus"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tLkt7
                )}
              >
                {"A Digital Designer"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__amVbN
                )}
              >
                {
                  "A Content creator, Social media manager and a Marketing expert"
                }
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mrk0Z
                )}
              >
                {
                  "He has strong ability to collaborate and\ncommunicate with cross functional teams, including developers, project managers and stakeholders.."
                }
              </div>

              <div
                data-plasmic-name={"ademola"}
                data-plasmic-override={overrides.ademola}
                className={classNames(projectcss.all, sty.ademola)}
              >
                <div
                  data-plasmic-name={"_16766661322111"}
                  data-plasmic-override={overrides._16766661322111}
                  className={classNames(projectcss.all, sty._16766661322111)}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yxYw
                )}
              >
                {"Ademola Paul"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bN4M
                )}
              >
                {
                  "A multi-disciplinary designer\nand developer. He specializes in brand design, product design, web development and mobile app development."
                }
              </div>

              <div
                data-plasmic-name={"line3"}
                data-plasmic-override={overrides.line3}
                className={classNames(projectcss.all, sty.line3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vzGo
                )}
              >
                {"Have a project in mind?\nLet’s get to work"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6R4Sf
                )}
              >
                {"Pevilab"}
              </div>

              <div
                data-plasmic-name={"rectangle12"}
                data-plasmic-override={overrides.rectangle12}
                className={classNames(projectcss.all, sty.rectangle12)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zbMy
                )}
              >
                {"Contact Us"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Tp5S
                )}
              >
                {"+000 1111 2222"}
              </div>

              <Ellipse8Icon
                className={classNames(projectcss.all, sty.svg__oQjeX)}
                role={"img"}
              />

              <Ellipse8Icon
                className={classNames(projectcss.all, sty.svg__a4K5W)}
                role={"img"}
              />

              <Ellipse8Icon
                className={classNames(projectcss.all, sty.svg___7HP6N)}
                role={"img"}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ooj3X)}
                displayHeight={"41.339px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"33.575px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/pevilab/images/group2.svg",
                  fullWidth: 33.575,
                  fullHeight: 41.339,
                  aspectRatio: 0.809524
                }}
              />

              <Xmlid826Icon
                className={classNames(projectcss.all, sty.svg__ktvqB)}
                role={"img"}
              />

              <div
                data-plasmic-name={"linkedin"}
                data-plasmic-override={overrides.linkedin}
                className={classNames(projectcss.all, sty.linkedin)}
              >
                <Vector2Icon
                  className={classNames(projectcss.all, sty.svg__e8KoG)}
                  role={"img"}
                />

                <Vector3Icon
                  className={classNames(projectcss.all, sty.svg__vGhV)}
                  role={"img"}
                />

                <Vector4Icon
                  className={classNames(projectcss.all, sty.svg__eUr3)}
                  role={"img"}
                />

                <Group3Icon
                  className={classNames(projectcss.all, sty.svg___57Tjq)}
                  role={"img"}
                />

                <Vector5Icon
                  className={classNames(projectcss.all, sty.svg__ihylk)}
                  role={"img"}
                />

                <Vector6Icon
                  className={classNames(projectcss.all, sty.svg__xD6Oi)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"rectangle13"}
                data-plasmic-override={overrides.rectangle13}
                className={classNames(projectcss.all, sty.rectangle13)}
              />

              <div
                data-plasmic-name={"rectangle15"}
                data-plasmic-override={overrides.rectangle15}
                className={classNames(projectcss.all, sty.rectangle15)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1NZ9C
                )}
              >
                {
                  "We are a full-service creative agency, with teams of \ntalented experts ready to help you build your product.\nWe work closely with clients to understand their expertise\nto develop effective and engaging solutions that help\nbusinesses stand out in the competitive market.\n\nOur services includes Branding, Graphic design,\nWeb and mobile development, Content creation,\nSocial media management, advertising and marketing."
                }
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cHuQq
                )}
              >
                {
                  "We are a full-service creative agency, with teams of \ntalented experts ready to help you build your product.\nWe work closely with clients to understand their expertise\nto develop effective and engaging solutions that help\nbusinesses stand out in the competitive market.\n\nOur services includes Branding, Graphic design,\nWeb and mobile development, Content creation,\nSocial media management, advertising and marketing."
                }
              </div>

              <div
                data-plasmic-name={"line4"}
                data-plasmic-override={overrides.line4}
                className={classNames(projectcss.all, sty.line4)}
              />

              <Line4Icon
                className={classNames(projectcss.all, sty.svg__n9S7)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___78PJc
                )}
              >
                {"Send Email"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qpNw2
                )}
              >
                {"Follow Us"}
              </div>

              <Ellipse9Icon
                className={classNames(projectcss.all, sty.svg__wNq5Y)}
                role={"img"}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___0Sfve)}
                displayHeight={"65px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"88px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/pevilab/images/quotationMarkIcon1.svg",
                  fullWidth: 88,
                  fullHeight: 65,
                  aspectRatio: 1.353846
                }}
              />

              <div
                data-plasmic-name={"frame1"}
                data-plasmic-override={overrides.frame1}
                className={classNames(projectcss.all, sty.frame1)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ter)}
                  displayHeight={"211px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"334px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/pevilab/images/rectangle16.svg",
                    fullWidth: 334,
                    fullHeight: 211,
                    aspectRatio: 1.582938
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bUfBq
                  )}
                >
                  {"Esther Howard"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mo2Bz
                  )}
                >
                  {
                    "I cannot recommend this agency enough! Their team is full of creative geniuses who were able to take my vague ..."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8PJzq
                  )}
                >
                  {"CEO Afrina"}
                </div>
              </div>

              <div
                data-plasmic-name={"frame2"}
                data-plasmic-override={overrides.frame2}
                className={classNames(projectcss.all, sty.frame2)}
              >
                <div
                  data-plasmic-name={"maskGroup"}
                  data-plasmic-override={overrides.maskGroup}
                  className={classNames(projectcss.all, sty.maskGroup)}
                >
                  <div
                    data-plasmic-name={"unsplashZpzf7TLjGA"}
                    data-plasmic-override={overrides.unsplashZpzf7TLjGA}
                    className={classNames(
                      projectcss.all,
                      sty.unsplashZpzf7TLjGa
                    )}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u3ASg
                  )}
                >
                  {"Eleanor Pena"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tUusv
                  )}
                >
                  {
                    "I cannot recommend this agency enough! Their team is full of creative geniuses who were able to take my vague ..."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lGvwQ
                  )}
                >
                  {"MCG Rentals"}
                </div>
              </div>

              <div
                data-plasmic-name={"frame3"}
                data-plasmic-override={overrides.frame3}
                className={classNames(projectcss.all, sty.frame3)}
              >
                <div
                  data-plasmic-name={"maskGroup2"}
                  data-plasmic-override={overrides.maskGroup2}
                  className={classNames(projectcss.all, sty.maskGroup2)}
                >
                  <div
                    data-plasmic-name={"unsplashGhMSApoKo0"}
                    data-plasmic-override={overrides.unsplashGhMSApoKo0}
                    className={classNames(
                      projectcss.all,
                      sty.unsplashGhMsApoKo0
                    )}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bsC41
                  )}
                >
                  {"Jacob Jones"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__toCdi
                  )}
                >
                  {
                    "I cannot recommend this agency enough! Their team is full of creative geniuses who were able to take my vague ..."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__md84A
                  )}
                >
                  {"Sales solution"}
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(projectcss.all, sty.rectangle17)}
              />

              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(projectcss.all, sty.rectangle18)}
              />

              <Ellipse10Icon
                className={classNames(projectcss.all, sty.svg__pSdU)}
                role={"img"}
              />

              <Ellipse11Icon
                className={classNames(projectcss.all, sty.svg__kx7Hx)}
                role={"img"}
              />

              <Ellipse12Icon
                className={classNames(projectcss.all, sty.svg__uE50B)}
                role={"img"}
              />

              <Ellipse11Icon
                className={classNames(projectcss.all, sty.svg___5W1Sy)}
                role={"img"}
              />

              <Ellipse11Icon
                className={classNames(projectcss.all, sty.svg__bxmr2)}
                role={"img"}
              />

              <div
                data-plasmic-name={"triangleBottomArrowIcon1"}
                data-plasmic-override={overrides.triangleBottomArrowIcon1}
                className={classNames(
                  projectcss.all,
                  sty.triangleBottomArrowIcon1
                )}
              >
                <Group4Icon
                  className={classNames(projectcss.all, sty.svg___3VCCv)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"triangleBottomArrowIcon2"}
                data-plasmic-override={overrides.triangleBottomArrowIcon2}
                className={classNames(
                  projectcss.all,
                  sty.triangleBottomArrowIcon2
                )}
              >
                <Group5Icon
                  className={classNames(projectcss.all, sty.svg__lHyBv)}
                  role={"img"}
                />
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div
              data-plasmic-name={"iPhone14Pro1"}
              data-plasmic-override={overrides.iPhone14Pro1}
              className={classNames(projectcss.all, sty.iPhone14Pro1)}
            >
              <div
                data-plasmic-name={"bg2"}
                data-plasmic-override={overrides.bg2}
                className={classNames(projectcss.all, sty.bg2)}
              />

              <div
                data-plasmic-name={"blur7"}
                data-plasmic-override={overrides.blur7}
                className={classNames(projectcss.all, sty.blur7)}
              />

              <div
                data-plasmic-name={"blur8"}
                data-plasmic-override={overrides.blur8}
                className={classNames(projectcss.all, sty.blur8)}
              />

              <div
                data-plasmic-name={"blur9"}
                data-plasmic-override={overrides.blur9}
                className={classNames(projectcss.all, sty.blur9)}
              />

              <div
                data-plasmic-name={"blur10"}
                data-plasmic-override={overrides.blur10}
                className={classNames(projectcss.all, sty.blur10)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__clMjo
                )}
              >
                {"Pevilab"}
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__dHlw0)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__f6Lqf)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Line6Icon
                  className={classNames(projectcss.all, sty.svg__tAw07)}
                  role={"img"}
                />
              ) : null}

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qzHd4
                )}
              >
                {"Trust by 100+ of Companies"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fDVl
                )}
              >
                {"Simplify Intricate\nApplications For\nUsers"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nTpQr
                )}
              >
                {
                  "We are a full-service creative agency, with teams of \ntalented experts ready to help you build your product.\nWe work closely with clients to understand their expertise\nto develop effective and engaging solutions that help\nbusinesses stand out in the competitive market.\n\nOur services includes Branding, Graphic design,\nWeb and mobile development, Content creation,\nSocial media management, advertising and marketing."
                }
              </div>

              <div
                data-plasmic-name={"blackPic2"}
                data-plasmic-override={overrides.blackPic2}
                className={classNames(projectcss.all, sty.blackPic2)}
              />

              <div
                data-plasmic-name={"rectangle11"}
                data-plasmic-override={overrides.rectangle11}
                className={classNames(projectcss.all, sty.rectangle11)}
              />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Ellipse13Icon
                  className={classNames(projectcss.all, sty.svg__z30Le)}
                  role={"img"}
                />
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <RedHeartIcon2Icon
                  className={classNames(projectcss.all, sty.svg__iIzGp)}
                  role={"img"}
                />
              ) : null}

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p9X9N
                )}
              >
                {"100+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ovjJk
                )}
              >
                {"Company Projects"}
              </div>

              <div
                data-plasmic-name={"line5"}
                data-plasmic-override={overrides.line5}
                className={classNames(projectcss.all, sty.line5)}
              />

              <div
                data-plasmic-name={"rectangle16"}
                data-plasmic-override={overrides.rectangle16}
                className={classNames(projectcss.all, sty.rectangle16)}
              />

              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(projectcss.all, sty.rectangle19)}
              />

              <div
                data-plasmic-name={"rectangle20"}
                data-plasmic-override={overrides.rectangle20}
                className={classNames(projectcss.all, sty.rectangle20)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sr4Ls
                )}
              >
                {"10+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___64RdY
                )}
              >
                {"25+"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6A0P
                )}
              >
                {"Years Of Experience"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uIuSo
                )}
              >
                {"Trusted Partners"}
              </div>

              <div
                data-plasmic-name={"qualityBadgeStarIcon2"}
                data-plasmic-override={overrides.qualityBadgeStarIcon2}
                className={classNames(
                  projectcss.all,
                  sty.qualityBadgeStarIcon2
                )}
              >
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Group6Icon
                    className={classNames(projectcss.all, sty.svg___9BDK)}
                    role={"img"}
                  />
                ) : null}
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3VNcc)}
                  displayHeight={"22px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"30px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/pevilab/images/commitmentIcon1.svg",
                    fullWidth: 30,
                    fullHeight: 22,
                    aspectRatio: 1.363636
                  }}
                />
              ) : null}

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(projectcss.all, sty.rectangle4)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xmlRg
                )}
              >
                {"Learn More"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jYdw0
                )}
              >
                {"Contact Us"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__epB2T
                )}
              >
                {"Explore Our Services"}
              </div>

              <div
                data-plasmic-name={"r15"}
                data-plasmic-override={overrides.r15}
                className={classNames(projectcss.all, sty.r15)}
              >
                <div
                  data-plasmic-name={"lline3"}
                  data-plasmic-override={overrides.lline3}
                  className={classNames(projectcss.all, sty.lline3)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7PLaQ
                  )}
                >
                  {"Web UI/UX\nDesign"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fHj
                  )}
                >
                  {"Explore"}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line2Icon
                    className={classNames(projectcss.all, sty.svg__bFrme)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse3Icon
                    className={classNames(projectcss.all, sty.svg__jzWq9)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__khR)}
                    displayHeight={"18px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"22px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/pevilab/images/thinArrowRightIcon4.svg",
                      fullWidth: 22,
                      fullHeight: 18,
                      aspectRatio: 1.222222
                    }}
                  />
                ) : null}
              </div>

              <div
                data-plasmic-name={"r16"}
                data-plasmic-override={overrides.r16}
                className={classNames(projectcss.all, sty.r16)}
              >
                <div
                  data-plasmic-name={"lline4"}
                  data-plasmic-override={overrides.lline4}
                  className={classNames(projectcss.all, sty.lline4)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aITq
                  )}
                >
                  {"Web & Mobile\nDevelopment"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nycp
                  )}
                >
                  {"Explore"}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line2Icon
                    className={classNames(projectcss.all, sty.svg__rrVHl)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse3Icon
                    className={classNames(projectcss.all, sty.svg__mrucS)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___55Mqu)}
                    displayHeight={"18px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"22px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/pevilab/images/thinArrowRightIcon5.svg",
                      fullWidth: 22,
                      fullHeight: 18,
                      aspectRatio: 1.222222
                    }}
                  />
                ) : null}
              </div>

              <div
                data-plasmic-name={"r17"}
                data-plasmic-override={overrides.r17}
                className={classNames(projectcss.all, sty.r17)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ul9Ei
                  )}
                >
                  {"Brand Identity\nDesign & 3D\nDesign"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3HiKn
                  )}
                >
                  {"Explore"}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line7Icon
                    className={classNames(projectcss.all, sty.svg__rra3)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse3Icon
                    className={classNames(projectcss.all, sty.svg__ywLiC)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yKg9D)}
                    displayHeight={"18px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"22px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/pevilab/images/thinArrowRightIcon6.svg",
                      fullWidth: 22,
                      fullHeight: 18,
                      aspectRatio: 1.222222
                    }}
                  />
                ) : null}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nviom
                )}
              >
                {"We Design Digital\nProducts, Brands\nand Experience"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qBVph
                )}
              >
                {
                  "We are a full-service creative agency, with teams of \ntalented experts ready to help you build your product.\nWe work closely with clients to understand their expertise to develop effective and engaging solutions that help businesses stand out in the competitive market."
                }
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <ThinLongArrowRightIcon2Icon
                  className={classNames(projectcss.all, sty.svg__gXiC)}
                  role={"img"}
                />
              ) : null}

              <div
                data-plasmic-name={"rectangle21"}
                data-plasmic-override={overrides.rectangle21}
                className={classNames(projectcss.all, sty.rectangle21)}
              />

              <div
                data-plasmic-name={"_16784072378992"}
                data-plasmic-override={overrides._16784072378992}
                className={classNames(projectcss.all, sty._16784072378992)}
              />

              <div
                data-plasmic-name={"line6"}
                data-plasmic-override={overrides.line6}
                className={classNames(projectcss.all, sty.line6)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__odAx
                )}
              >
                {"Why Choose Us?"}
              </div>

              <div
                data-plasmic-name={"r18"}
                data-plasmic-override={overrides.r18}
                className={classNames(projectcss.all, sty.r18)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uir1T
                  )}
                >
                  {"Proven Track Records"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1LlAl
                  )}
                >
                  {"Specialized Experts"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iXl9D
                  )}
                >
                  {"Innovative Thinking"}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse4Icon
                    className={classNames(projectcss.all, sty.svg__xlDj)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse4Icon
                    className={classNames(projectcss.all, sty.svg__gMzBu)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Ellipse4Icon
                    className={classNames(projectcss.all, sty.svg__xhM0S)}
                    role={"img"}
                  />
                ) : null}

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nxpEk
                  )}
                >
                  {"01"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vmQbn
                  )}
                >
                  {"02"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u0Rl
                  )}
                >
                  {"03"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aFzNw
                  )}
                >
                  {
                    "We have a portfolio of successful projects and campaigns we’ve completed for previous clients, this prove our ability of consistent quality work and results."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__reQFj
                  )}
                >
                  {
                    "Pevilab is a team of specialized experts that have several experience and \nknowledge in their area of field such as web development, designs and more."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x1IuG
                  )}
                >
                  {
                    "We provide fresh and Innovative ideas that makes businesses stand out from \ntheir competitors and help connect them with their ideal customers."
                  }
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line4Icon
                    className={classNames(projectcss.all, sty.svg__tpqBo)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line4Icon
                    className={classNames(projectcss.all, sty.svg__wwUfJ)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Line4Icon
                    className={classNames(projectcss.all, sty.svg__lFv2S)}
                    role={"img"}
                  />
                ) : null}
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "webpage",
    "bg",
    "blur1",
    "blur2",
    "blur4",
    "blur6",
    "blur5",
    "blur3",
    "rectangle1",
    "rectangle2",
    "blackPic1",
    "rectangle6",
    "line",
    "line2",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "qualityBadgeStarIcon",
    "r1",
    "lline1",
    "r12",
    "lline2",
    "r13",
    "r14",
    "rectangle14",
    "rectangle10",
    "_16784072378991",
    "ay",
    "_16784110698861",
    "ay2",
    "_16784110698862",
    "wonder",
    "_1678444491112",
    "mekus",
    "_1678444491125",
    "ademola",
    "_16766661322111",
    "line3",
    "rectangle12",
    "linkedin",
    "rectangle13",
    "rectangle15",
    "line4",
    "frame1",
    "frame2",
    "maskGroup",
    "unsplashZpzf7TLjGA",
    "frame3",
    "maskGroup2",
    "unsplashGhMSApoKo0",
    "rectangle17",
    "rectangle18",
    "triangleBottomArrowIcon1",
    "triangleBottomArrowIcon2",
    "iPhone14Pro1",
    "bg2",
    "blur7",
    "blur8",
    "blur9",
    "blur10",
    "blackPic2",
    "rectangle11",
    "line5",
    "rectangle16",
    "rectangle19",
    "rectangle20",
    "qualityBadgeStarIcon2",
    "rectangle3",
    "rectangle4",
    "r15",
    "lline3",
    "r16",
    "lline4",
    "r17",
    "rectangle21",
    "_16784072378992",
    "line6",
    "r18"
  ],

  webpage: [
    "webpage",
    "bg",
    "blur1",
    "blur2",
    "blur4",
    "blur6",
    "blur5",
    "blur3",
    "rectangle1",
    "rectangle2",
    "blackPic1",
    "rectangle6",
    "line",
    "line2",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "qualityBadgeStarIcon",
    "r1",
    "lline1",
    "r12",
    "lline2",
    "r13",
    "r14",
    "rectangle14",
    "rectangle10",
    "_16784072378991",
    "ay",
    "_16784110698861",
    "ay2",
    "_16784110698862",
    "wonder",
    "_1678444491112",
    "mekus",
    "_1678444491125",
    "ademola",
    "_16766661322111",
    "line3",
    "rectangle12",
    "linkedin",
    "rectangle13",
    "rectangle15",
    "line4",
    "frame1",
    "frame2",
    "maskGroup",
    "unsplashZpzf7TLjGA",
    "frame3",
    "maskGroup2",
    "unsplashGhMSApoKo0",
    "rectangle17",
    "rectangle18",
    "triangleBottomArrowIcon1",
    "triangleBottomArrowIcon2"
  ],

  bg: ["bg"],
  blur1: ["blur1"],
  blur2: ["blur2"],
  blur4: ["blur4"],
  blur6: ["blur6"],
  blur5: ["blur5"],
  blur3: ["blur3"],
  rectangle1: ["rectangle1"],
  rectangle2: ["rectangle2"],
  blackPic1: ["blackPic1"],
  rectangle6: ["rectangle6"],
  line: ["line"],
  line2: ["line2"],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  qualityBadgeStarIcon: ["qualityBadgeStarIcon"],
  r1: ["r1", "lline1"],
  lline1: ["lline1"],
  r12: ["r12", "lline2"],
  lline2: ["lline2"],
  r13: ["r13"],
  r14: ["r14"],
  rectangle14: ["rectangle14"],
  rectangle10: ["rectangle10"],
  _16784072378991: ["_16784072378991"],
  ay: ["ay", "_16784110698861"],
  _16784110698861: ["_16784110698861"],
  ay2: ["ay2", "_16784110698862"],
  _16784110698862: ["_16784110698862"],
  wonder: ["wonder", "_1678444491112"],
  _1678444491112: ["_1678444491112"],
  mekus: ["mekus", "_1678444491125"],
  _1678444491125: ["_1678444491125"],
  ademola: ["ademola", "_16766661322111"],
  _16766661322111: ["_16766661322111"],
  line3: ["line3"],
  rectangle12: ["rectangle12"],
  linkedin: ["linkedin"],
  rectangle13: ["rectangle13"],
  rectangle15: ["rectangle15"],
  line4: ["line4"],
  frame1: ["frame1"],
  frame2: ["frame2", "maskGroup", "unsplashZpzf7TLjGA"],
  maskGroup: ["maskGroup", "unsplashZpzf7TLjGA"],
  unsplashZpzf7TLjGA: ["unsplashZpzf7TLjGA"],
  frame3: ["frame3", "maskGroup2", "unsplashGhMSApoKo0"],
  maskGroup2: ["maskGroup2", "unsplashGhMSApoKo0"],
  unsplashGhMSApoKo0: ["unsplashGhMSApoKo0"],
  rectangle17: ["rectangle17"],
  rectangle18: ["rectangle18"],
  triangleBottomArrowIcon1: ["triangleBottomArrowIcon1"],
  triangleBottomArrowIcon2: ["triangleBottomArrowIcon2"],
  iPhone14Pro1: [
    "iPhone14Pro1",
    "bg2",
    "blur7",
    "blur8",
    "blur9",
    "blur10",
    "blackPic2",
    "rectangle11",
    "line5",
    "rectangle16",
    "rectangle19",
    "rectangle20",
    "qualityBadgeStarIcon2",
    "rectangle3",
    "rectangle4",
    "r15",
    "lline3",
    "r16",
    "lline4",
    "r17",
    "rectangle21",
    "_16784072378992",
    "line6",
    "r18"
  ],

  bg2: ["bg2"],
  blur7: ["blur7"],
  blur8: ["blur8"],
  blur9: ["blur9"],
  blur10: ["blur10"],
  blackPic2: ["blackPic2"],
  rectangle11: ["rectangle11"],
  line5: ["line5"],
  rectangle16: ["rectangle16"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  qualityBadgeStarIcon2: ["qualityBadgeStarIcon2"],
  rectangle3: ["rectangle3"],
  rectangle4: ["rectangle4"],
  r15: ["r15", "lline3"],
  lline3: ["lline3"],
  r16: ["r16", "lline4"],
  lline4: ["lline4"],
  r17: ["r17"],
  rectangle21: ["rectangle21"],
  _16784072378992: ["_16784072378992"],
  line6: ["line6"],
  r18: ["r18"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    webpage: makeNodeComponent("webpage"),
    bg: makeNodeComponent("bg"),
    blur1: makeNodeComponent("blur1"),
    blur2: makeNodeComponent("blur2"),
    blur4: makeNodeComponent("blur4"),
    blur6: makeNodeComponent("blur6"),
    blur5: makeNodeComponent("blur5"),
    blur3: makeNodeComponent("blur3"),
    rectangle1: makeNodeComponent("rectangle1"),
    rectangle2: makeNodeComponent("rectangle2"),
    blackPic1: makeNodeComponent("blackPic1"),
    rectangle6: makeNodeComponent("rectangle6"),
    line: makeNodeComponent("line"),
    line2: makeNodeComponent("line2"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    qualityBadgeStarIcon: makeNodeComponent("qualityBadgeStarIcon"),
    r1: makeNodeComponent("r1"),
    lline1: makeNodeComponent("lline1"),
    r12: makeNodeComponent("r12"),
    lline2: makeNodeComponent("lline2"),
    r13: makeNodeComponent("r13"),
    r14: makeNodeComponent("r14"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle10: makeNodeComponent("rectangle10"),
    _16784072378991: makeNodeComponent("_16784072378991"),
    ay: makeNodeComponent("ay"),
    _16784110698861: makeNodeComponent("_16784110698861"),
    ay2: makeNodeComponent("ay2"),
    _16784110698862: makeNodeComponent("_16784110698862"),
    wonder: makeNodeComponent("wonder"),
    _1678444491112: makeNodeComponent("_1678444491112"),
    mekus: makeNodeComponent("mekus"),
    _1678444491125: makeNodeComponent("_1678444491125"),
    ademola: makeNodeComponent("ademola"),
    _16766661322111: makeNodeComponent("_16766661322111"),
    line3: makeNodeComponent("line3"),
    rectangle12: makeNodeComponent("rectangle12"),
    linkedin: makeNodeComponent("linkedin"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle15: makeNodeComponent("rectangle15"),
    line4: makeNodeComponent("line4"),
    frame1: makeNodeComponent("frame1"),
    frame2: makeNodeComponent("frame2"),
    maskGroup: makeNodeComponent("maskGroup"),
    unsplashZpzf7TLjGA: makeNodeComponent("unsplashZpzf7TLjGA"),
    frame3: makeNodeComponent("frame3"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    unsplashGhMSApoKo0: makeNodeComponent("unsplashGhMSApoKo0"),
    rectangle17: makeNodeComponent("rectangle17"),
    rectangle18: makeNodeComponent("rectangle18"),
    triangleBottomArrowIcon1: makeNodeComponent("triangleBottomArrowIcon1"),
    triangleBottomArrowIcon2: makeNodeComponent("triangleBottomArrowIcon2"),
    iPhone14Pro1: makeNodeComponent("iPhone14Pro1"),
    bg2: makeNodeComponent("bg2"),
    blur7: makeNodeComponent("blur7"),
    blur8: makeNodeComponent("blur8"),
    blur9: makeNodeComponent("blur9"),
    blur10: makeNodeComponent("blur10"),
    blackPic2: makeNodeComponent("blackPic2"),
    rectangle11: makeNodeComponent("rectangle11"),
    line5: makeNodeComponent("line5"),
    rectangle16: makeNodeComponent("rectangle16"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    qualityBadgeStarIcon2: makeNodeComponent("qualityBadgeStarIcon2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle4: makeNodeComponent("rectangle4"),
    r15: makeNodeComponent("r15"),
    lline3: makeNodeComponent("lline3"),
    r16: makeNodeComponent("r16"),
    lline4: makeNodeComponent("lline4"),
    r17: makeNodeComponent("r17"),
    rectangle21: makeNodeComponent("rectangle21"),
    _16784072378992: makeNodeComponent("_16784072378992"),
    line6: makeNodeComponent("line6"),
    r18: makeNodeComponent("r18"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
